# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Testing For PRs

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-version: # See https://endoflife.date/docker-engine / https://download.docker.com/linux/static/stable/x86_64/
          - "v25.0.5"  # 2024-01 --> EOL ?
          - "v28.3.1"  # 2025-04 --> EOL ?
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: 21
          distribution: temurin
      - name: Set up Docker
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
        with:
          version: ${{ matrix.docker-version }}
          set-host: 'true'
      - run: docker swarm init
      - name: Build with Gradle
        run: ./gradlew assemble check