# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Testing For PRs

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-version: # See https://endoflife.date/docker-engine / https://download.docker.com/linux/static/stable/x86_64/
          - "v23.0.6"  # 2023-02 --> EOL ?
          - "v25.0.5"  # 2024-01 --> EOL ?
          - "v27.5.1"  # 2025-01 --> EOL ?
          - "v28.1.1"  # 2025-04 --> EOL ?
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 17
          distribution: temurin
      - name: Set up Docker
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
        with:
          version: ${{ matrix.docker-version }}
          set-host: 'true'
      - run: docker swarm init
      - name: Build with Gradle
        run: ./gradlew assemble check